# MINIPROJECT-LINEAR REGRESSION

**The aim is to predict the car price by training dataset using linear regression model**

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("car price dataset.csv")

In [3]:
df.describe()

Unnamed: 0         Year  Kilometers_Driven        Seats        Price
count  6019.000000  6019.000000       6.019000e+03  5977.000000  6019.000000
mean   3009.000000  2013.358199       5.873838e+04     5.278735     9.479468
std    1737.679967     3.269742       9.126884e+04     0.808840    11.187917
min       0.000000  1998.000000       1.710000e+02     0.000000     0.440000
25%    1504.500000  2011.000000       3.400000e+04     5.000000     3.500000
50%    3009.000000  2014.000000       5.300000e+04     5.000000     5.640000
75%    4513.500000  2016.000000       7.300000e+04     5.000000     9.950000
max    6018.000000  2019.000000       6.500000e+06    10.000000   160.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         6019 non-null   int64  
 1   Name               6019 non-null   object 
 2   Location           6019 non-null   object 
 3   Year               6019 non-null   int64  
 4   Kilometers_Driven  6019 non-null   int64  
 5   Fuel_Type          6019 non-null   object 
 6   Transmission       6019 non-null   object 
 7   Owner_Type         6019 non-null   object 
 8   Mileage            6017 non-null   object 
 9   Engine             5983 non-null   object 
 10  Power              5983 non-null   object 
 11  Seats              5977 non-null   float64
 12  Price              6019 non-null   float64
dtypes: float64(2), int64(3), object(8)
memory usage: 611.4+ KB


**preprocesssing required**

            we have null values in 4 columns mileage,engine,power,seats

In [11]:
print(df.columns)

Index(['Unnamed: 0', 'Name', 'Location', 'Year', 'Kilometers_Driven',
       'Fuel_Type', 'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power',
       'Seats', 'Price'],
      dtype='object')


In [12]:
df.head()

Unnamed: 0                              Name    Location  Year  \
0           0            Maruti Wagon R LXI CNG      Mumbai  2010   
1           1  Hyundai Creta 1.6 CRDi SX Option        Pune  2015   
2           2                      Honda Jazz V     Chennai  2011   
3           3                 Maruti Ertiga VDI     Chennai  2012   
4           4   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013   

   Kilometers_Driven Fuel_Type Transmission Owner_Type     Mileage   Engine  \
0              72000       CNG       Manual      First  26.6 km/kg   998 CC   
1              41000    Diesel       Manual      First  19.67 kmpl  1582 CC   
2              46000    Petrol       Manual      First   18.2 kmpl  1199 CC   
3              87000    Diesel       Manual      First  20.77 kmpl  1248 CC   
4              40670    Diesel    Automatic     Second   15.2 kmpl  1968 CC   

       Power  Seats  Price  
0  58.16 bhp    5.0   1.75  
1  126.2 bhp    5.0  12.50  
2   88.7 bhp    5.0   4.50  
3  88.76 bhp    7.0   6.00  
4  140.8 bhp    5.0  17.74

In [28]:
k=df['Seats'].mean()
df['Seats'].fillna(k,inplace=True)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         6019 non-null   int64  
 1   Name               6019 non-null   object 
 2   Location           6019 non-null   object 
 3   Year               6019 non-null   int64  
 4   Kilometers_Driven  6019 non-null   int64  
 5   Fuel_Type          6019 non-null   object 
 6   Transmission       6019 non-null   object 
 7   Owner_Type         6019 non-null   object 
 8   Mileage            6017 non-null   object 
 9   Engine             5983 non-null   object 
 10  Power              5983 non-null   object 
 11  Seats              6019 non-null   float64
 12  Price              6019 non-null   float64
dtypes: float64(2), int64(3), object(8)
memory usage: 611.4+ KB


In [33]:
x=df['Mileage'].dropna(inplace=True)

In [56]:
print(df['Power'].mode())
print(df['Engine'].mode())
df['Mileage'].mode()

0    74 bhp
dtype: object
0    1197 CC
dtype: object


0    17.0 kmpl
dtype: object

In [45]:
df['Engine'].fillna('1197 CC',inplace=True)

In [57]:
df['Power'].fillna('74 bhp',inplace=True)

In [48]:
df['Mileage'].fillna('17.0 kmpl',inplace=True)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6019 entries, 0 to 6018
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         6019 non-null   int64  
 1   Name               6019 non-null   object 
 2   Location           6019 non-null   object 
 3   Year               6019 non-null   int64  
 4   Kilometers_Driven  6019 non-null   int64  
 5   Fuel_Type          6019 non-null   object 
 6   Transmission       6019 non-null   object 
 7   Owner_Type         6019 non-null   object 
 8   Mileage            6019 non-null   object 
 9   Engine             6019 non-null   object 
 10  Power              6019 non-null   object 
 11  Seats              6019 non-null   float64
 12  Price              6019 non-null   float64
dtypes: float64(2), int64(3), object(8)
memory usage: 658.3+ KB


In [52]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
6014    False
6015    False
6016    False
6017    False
6018    False
Length: 6019, dtype: bool

In [53]:
df.drop_duplicates(inplace=True)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6019 entries, 0 to 6018
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         6019 non-null   int64  
 1   Name               6019 non-null   object 
 2   Location           6019 non-null   object 
 3   Year               6019 non-null   int64  
 4   Kilometers_Driven  6019 non-null   int64  
 5   Fuel_Type          6019 non-null   object 
 6   Transmission       6019 non-null   object 
 7   Owner_Type         6019 non-null   object 
 8   Mileage            6019 non-null   object 
 9   Engine             6019 non-null   object 
 10  Power              6019 non-null   object 
 11  Seats              6019 non-null   float64
 12  Price              6019 non-null   float64
dtypes: float64(2), int64(3), object(8)
memory usage: 658.3+ KB


**now the data preprocessing is completed**

**SPLITTING TRAINING AND TESTING DATA**

In [108]:
corr=df.corr()
print(corr)
corr.Price.sort_values(ascending=False).head(10)

                   Unnamed: 0      Year  Kilometers_Driven     Seats     Price
Unnamed: 0           1.000000  0.002354          -0.008734 -0.010804 -0.020275
Year                 0.002354  1.000000          -0.173048  0.012204  0.305327
Kilometers_Driven   -0.008734 -0.173048           1.000000  0.083072 -0.011493
Seats               -0.010804  0.012204           0.083072  1.000000  0.052118
Price               -0.020275  0.305327          -0.011493  0.052118  1.000000


Price                1.000000
Year                 0.305327
Seats                0.052118
Kilometers_Driven   -0.011493
Unnamed: 0          -0.020275
Name: Price, dtype: float64

**As the year has more correlation with price the independent variable is year**

In [98]:
x=df.iloc[:,[3]].values  #independent variable-->Year
y=df.iloc[:,[12]].values  #dependent variable-->Price

In [99]:
x

array([[2010],
       [2015],
       [2011],
       ...,
       [2012],
       [2013],
       [2011]], dtype=int64)

In [100]:
y

array([[ 1.75],
       [12.5 ],
       [ 4.5 ],
       ...,
       [ 2.9 ],
       [ 2.65],
       [ 2.5 ]])

In [101]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/4,random_state=0)

**linear regression model training**

In [102]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

**Testing**

In [103]:
y_pred=regressor.predict(x_test)

In [104]:
y_pred

array([[10.06088121],
       [ 5.83415222],
       [ 7.94751671],
       ...,
       [10.06088121],
       [12.1742457 ],
       [13.23092795]])

In [107]:
z=regressor.predict([[2011]])
z

array([[6.89083447]])

In [110]:
y=regressor.predict([[2023]])
y

array([[19.57102143]])